{{/*
Copyright 2020 HAProxy Technologies LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  namespace: {{ include "haproxy.namespace" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
  annotations:
{{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote}}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if or .Values.containerPorts .Values.service.additionalPorts }}
  ports:
  {{- with .Values.containerPorts }}
  {{- range $key, $port := . }}
  - name: {{ $key }}
    protocol: TCP
    port: {{ $port }}
    targetPort: {{ $key }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.additionalPorts }}
  {{- range $key, $port := . }}
  - name: {{ $key }}
    protocol: TCP
    port: {{ $port }}
    targetPort: {{ $key }}
  {{- end }}
  {{- end }}
  {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}-stats  # Cambia el nombre del servicio
  namespace: {{ include "haproxy.namespace" . }}  # Cambia el namespace si es necesario
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}  # Ajusta las etiquetas si es necesario
  annotations:
{{- range $key, $value := .Values.service2.annotations }}  # Usa las anotaciones del servicio 2
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  type: {{ .Values.service2.type }}  # Usa el tipo de servicio del servicio 2
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}  # Ajusta el selector si es necesario
  {{- if .Values.service2.externalTrafficPolicy }}  # Usa la política de tráfico externo del servicio 2
  externalTrafficPolicy: {{ .Values.service2.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service2.clusterIP }}  # Usa la IP de cluster del servicio 2
  clusterIP: {{ . | quote}}
  {{- end }}
  {{- with .Values.service2.loadBalancerIP }}  # Usa la IP del balanceador de carga del servicio 2
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service2.loadBalancerSourceRanges }}  # Usa los rangos de IP permitidos del servicio 2
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.service2.externalIPs }}  # Usa las IPs externas del servicio 2
  externalIPs:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if or .Values.service2.additionalPorts }}
  ports:
  {{- with .Values.service2.additionalPorts }}  # Usa puertos adicionales del servicio 2 si es necesario
  {{- range $key, $port := . }}
  - name: {{ $key }}
    protocol: TCP
    port: {{ $port }}
    targetPort: {{ $key }}
  {{- end }}
  {{- end }}
  {{- end }}


